### ISSUE TITLE
Please add support for "SourceHanNotoCJK.ttc"

### ISSUE THREAD

**Issue by ShikiSuen** [zr-tex8r/PXchfon#7]
https://github.com/adobe-fonts/source-han-super-otc/releases/download/20190603/SourceHanNotoCJK.ttc

https://github.com/adobe-fonts/source-han-super-otc/releases

One file includes all fonts from Noto CJK family and Source Han family.

**Comment by ShikiSuen** [comment]
Update: I tried to edit the pxchfon.sty by myself:
[pxchfon.sty.zip](https://github.com/zr-tex8r/PXchfon/files/3530847/pxchfon.sty.zip)

But I got errors when compiling the project.

Compiling with platex-ng (a component of aptex / ptex-ng):
<img width="685" alt="image" src="https://user-images.githubusercontent.com/3164826/63528265-9a111b00-c53d-11e9-82bc-a2d00759b07b.png">

Compiling with uplatex:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/3164826/63528286-a4cbb000-c53d-11e9-8da7-cb21b7f1da3d.png">

The project file content:
```
\documentclass[uplatex,a4paper]{jsarticle}
\usepackage[deluxe]{otf}
\usepackage[sourcehannotocjk]{pxchfon}
\begin{document}
\mcfamily
体は剣で出来ている
血潮は鉄で心は硝子
幾たびの戦場を越えて不敗
ただ一度の敗走もなく、
ただ一度の勝利もなし
担い手はここに独り
剣の丘で鉄を鍛つ
ならば我が生涯に意味は不要ず
この体は、
無限の剣で出来ていた。
\end{document}
```

**Comment by zr-tex8r** [comment]
> But I got errors when compiling the project.
>
> Compiling with platex-ng (a component of aptex / ptex-ng):

The japanese-otf package (`\usepackage{otf}`) as distributed by TeX Live cannot be used with the pTeX-ng engine. That is because the files in the package are encoded in ISO-2022-JP, which is not supported by pTeX-ng. (When pTeX/upTeX is concerned, ISO-2022-JP is really the safest choice because it goes well with any source encoding setting of the engine.)

If you really want to do `\usepackage{otf}` on pTeX-ng, then you need to convert the file `ajmacros.sty` (a file in japanese-otf) to UTF-8.

Or alternatively, you can employ the option `nomacros`, that is `usepackage[nomacros]{otf}`, which goes well at the cost of disabling some convenience commands such as `\ajMaru`.

**Comment by ShikiSuen** [comment]
@zr-tex8r 

ご助言ありがとうございます。
今までShift-JIS以外の日本語のエンコーディングは知りませんでした。
ApTeXのISO-2022-JPサポートはできるかどうか、こちらは後でApTeXの開発者と話します。

話を戻りましょう。
PXchfonの「SourceHanNotoCJK.ttc」に対する公式のサポート、その予定はございますか。

**Comment by zr-tex8r** [comment]
> Compiling with uplatex:

In this time, the error is due to the modified pxchfon.sty.

```diff
@@ -1975,6 +1977,9 @@
    {NotoSansJP-Regular.otf}{NotoSansJP-Bold.otf}%
    {NotoSansJP-Black.otf}{NotoSansJP-Medium.otf}%
    {NotoSansJP-Medium.otf}}
+% Source Han Sans / Serif + Noto Sans/Serif CJK, big-ass OTC"
+\pxcz@declare@preset{sourcehannotocjk}{%
+  \pxcz@multiweight{:0:SourceHanNotoCJK.ttc}}
 %(alias)
 \pxcz@declare@preset@alias{hiragino}{hiragino-pro}
 \pxcz@declare@preset@alias{noEmbed}{noembed}
```

The macro `\pxcz@multiweight` must always take eight arguments.

```latex
\pxcz@declare@preset{sourcehan}{%
  \pxcz@multiweight{SourceHanSerif-Light.otf}%
   {SourceHanSerif-Regular.otf}{SourceHanSerif-Bold.otf}%
   {SourceHanSans-Regular.otf}{SourceHanSans-Bold.otf}%
   {SourceHanSans-Heavy.otf}{SourceHanSans-Medium.otf}%
   {SourceHanSans-Medium.otf}}
\pxcz@declare@preset{noto}{%
  \pxcz@multiweight{NotoSerifCJKjp-Light.otf}%
   {NotoSerifCJKjp-Regular.otf}{NotoSerifCJKjp-Bold.otf}%
   {NotoSansCJKjp-Regular.otf}{NotoSansCJKjp-Bold.otf}%
   {NotoSansCJKjp-Black.otf}{NotoSansCJKjp-Medium.otf}%
   {NotoSansCJKjp-Medium.otf}}
```

Moreover, when you want to make `sourcehannotocjk` work exactly like `sourcehan`, you must specify ”the same font”. Namely:

* The first argument is `SourceHanSerif-Light.otf`, which file contains (only) “SourceHanSerif-Light”. And in the ultra-otc file SourceHanNotoCJK.ttc this font is located at position 49. So you must write `:49:SourceHanNotoCJK.ttc` for `sourcehannotocjk`.
* The second argument is `SourceHanSerif-Regular.otf`. You must write `:53:SourceHanNotoCJK.ttc` for `sourcehannotocjk`.

And so on…, then the correct solution is:

```latex
\pxcz@declare@preset{sourcehannotocjk}{%
  \pxcz@multiweight{:49:SourceHanNotoCJK.ttc}%
   {:53:SourceHanNotoCJK.ttc}{:65:SourceHanNotoCJK.ttc}%
   {:15:SourceHanNotoCJK.ttc}{:30:SourceHanNotoCJK.ttc}%
   {:40:SourceHanNotoCJK.ttc}{:25:SourceHanNotoCJK.ttc}%
   {:25:SourceHanNotoCJK.ttc}}
```

If you want to make `sourcehannotocjk` work exactly like `noto`, then the correct solution is:

```latex
\pxcz@declare@preset{sourcehannotocjk}{%
  \pxcz@multiweight{:192:SourceHanNotoCJK.ttc}%
   {:196:SourceHanNotoCJK.ttc}{:208:SourceHanNotoCJK.ttc}%
   {:158:SourceHanNotoCJK.ttc}{:173:SourceHanNotoCJK.ttc}%
   {:183:SourceHanNotoCJK.ttc}{:168:SourceHanNotoCJK.ttc}%
   {:168:SourceHanNotoCJK.ttc}}
```

**Comment by zr-tex8r** [comment]
> PXchfonの「SourceHanNotoCJK.ttc」に対する公式のサポート、その予定はございますか。

で、本題なんですが、これに関しては残念ながら I'm not so inclined to do so なのですよね。

The main problem is that we are required to specify the correct “position number” (such as `53` or `208`) to use the ultra-OTC file. *Are the numbers stable?* I don't think so. When the repertoire of Source Han and/or Noto CJK changes, the position numbers will be likely to change. As a matter of fact, the super-OTC (yes, merely super and not mega or ultra…) of Source Han Sans has changed the position numbers during the update from v1 to v2, because some languages are added.

So the support for such Super/Mega/Ultra-things will inevitably be version-dependent. That is rather confusing from users' point of view.

**Comment by ShikiSuen** [comment]
おかげで色々わかりました。お返事ありがとうございます。
